init:
- appveyor version
- ps: Update-AppveyorBuild -Message "Image '$env:APPVEYOR_BUILD_WORKER_IMAGE'@'$env:APPVEYOR_BUILD_WORKER_CLOUD' cloud. $env:APPVEYOR_REPO_COMMIT_MESSAGE"
- sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
- sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
- sh: |
    # Only use colors if connected to a terminal
    if [ -t 1 ]; then
      RED=$(printf '\033[31m')
      GREEN=$(printf '\033[32m')
      YELLOW=$(printf '\033[33m')
      BLUE=$(printf '\033[34m')
      BOLD=$(printf '\033[1m')
      RESET=$(printf '\033[m')
      NC=$(printf '\033[m')
    else
      RED=""
      GREEN=""
      YELLOW=""
      BLUE=""
      BOLD=""
      RESET=""
      NC=""
    fi
    
stack:
  - ${NODE_STACK} 


test_script:
     - sh: nvm --version
     - sh: nvm list


     - sh: |
        echo "Latest ${NODE_MAJOR}.x:"
        nvm use $NODE_MAJOR
        node --version


     - sh: |
        if ! nvm use ${NODE_VERSION}; then 
            echo "${RED} nvm cant use version '${version}' ${NC}"
            exit 1
        fi
        node --version >${APPVEYOR_BUILD_FOLDER}/${NODE_VERSION}.txt
        if [ $(node --version) = "v${NODE_VERSION}" ]; then
            echo "${GREEN}Correct version ${NODE_STACK}${NC}"
        else
            exit 1
        fi

artifacts:
  - path: '**\*.txt'

build: off
